/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Usuario;

import java.util.Scanner;

/**
 *
 * @author emilio
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnVerificar = new javax.swing.JButton();
        lblComentario = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese su Contraseña");

        btnVerificar.setText("Verificar");
        btnVerificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerificarMouseClicked(evt);
            }
        });
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        lblResultado.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComentario)
                    .addComponent(btnVerificar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResultado)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnVerificar)
                .addGap(18, 18, 18)
                .addComponent(lblComentario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultado)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerificarMouseClicked

        int linea1 = 0, linea2 = 0, linea3 = 0, linea4 = 0, linea5 = 0, linea6 = 0, linea7 = 0, linea8 = 0;
        int inf1 = 0, sup1 = 0, inf2 = 0, sup2 = 0, inf3 = 0, sup3 = 0, inf4 = 0, sup4 = 0;
        
        
        String Password = new String(txtContrasena.getPassword());
        Scanner scan = new Scanner(System.in);
      
        
        if (Password.length()< linea1)
        {
           lblComentario.setText("La contraseña no pude tener menos de 6 caracteres..."); 
        }
        else
        {
            int Puntuacion = 0;  
            int Mayuscula = 0; 
            int Minuscula = 0;
            int Numeros = 0;
            int Simbolos = 0;
            
           lblComentario.setText(""); 
           
           //Puntuación= (Número de la segunda línea) * (largo de contraseña ingresada)
           Puntuacion += 3*Password.length();
           
           //Encontrar las mayúsculas, minúsculas, símbolos y números
            for (int i = 0; i < Password.length(); i++) {
                char ch = Password.charAt(i);
                
                if (ch>= 'A' && ch <='Z') {
                    Mayuscula++;
                }
                else if (ch>='a' && ch<='z') {
                    Minuscula++;
                }
                else if (ch == '/' || ch == '¿' || ch == '%' || ch == '$' || ch == '#' ) {
                    Simbolos++;
                }
                else {
                    Numeros++;
                }
            }
            
            //Puntuación= Puntuación + [(Número de la tercer línea)*(total de Mayúsculas ingresadas)]
            if (Mayuscula != 0) {
                
                Puntuacion += 2*Mayuscula;
            }
            
            
            //Puntuación= Puntuación+ [(total de letras ingresadas)+ (Número de la cuarta línea)
            if (Mayuscula != 0 || Minuscula != 0) {
                
                Puntuacion += Mayuscula + Minuscula + 1;
            }
            
            //Puntuación= Puntuación+ [(total de números ingresados)+ (Número de la quinta línea)
            if (Numeros != 0) {
                Puntuacion += Numeros + 2;
            }
            
            //Puntuación= Puntuación + (total de símbolos ingresados) *[(largo de cadena) + (Número de la sexta línea) [/¿?%$#]
            if (Simbolos != 0) {
                
                Puntuacion += Simbolos * (Password.length() + 4);
            }         
            
            //Si hay sólo letras: Puntuación – (Número de la séptima línea)
            if (Numeros == 0 && Simbolos == 0) {
                
                Puntuacion -= 6;
            }
            
            //Si hay sólo números: Puntuación – (Número de la octava línea)
            
            if (Mayuscula == 0 && Minuscula == 0 && Simbolos == 0) {
                
                Puntuacion -= 3;
            }
            
            //Imprimir comentario sobre seguridad de contraseña
            
            if (Puntuacion >= 0 && Puntuacion <= 25) {
                
                lblComentario.setText("Contraseña Insegura...");
            }
            else if (Puntuacion >= 26 && Puntuacion <= 35) {
                
                lblComentario.setText("Contraseña poco Segura...");
            }
            else if (Puntuacion >= 36 && Puntuacion <= 50) {
                
                lblComentario.setText("Contraseña Segura...");
            }
            else if (Puntuacion >= 51) {
                
                lblComentario.setText("Contraseña muy Segura...");
            }
            
            lblResultado.setText(String.valueOf(Puntuacion));
            
            
               
           
        }
        
        
    }//GEN-LAST:event_btnVerificarMouseClicked

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables
}
