/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Usuario;

import java.util.Scanner;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author emilio
 */
public class login extends javax.swing.JFrame {
    
    int linea1 = 0, linea2 = 0, linea3 = 0, linea4 = 0, linea5 = 0, linea6 = 0, linea7 = 0, linea8 = 0;
    int inf1 = 0, sup1 = 0, inf2 = 0, sup2 = 0, inf3 = 0, sup3 = 0, inf4 = 0, sup4 = 0;
        
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnVerificar = new javax.swing.JButton();
        lblComentario = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btn_cargarResultados = new javax.swing.JButton();
        btn_cargarPuntuacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese su Contraseña");

        btnVerificar.setText("Verificar");
        btnVerificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerificarMouseClicked(evt);
            }
        });
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        lblResultado.setText("0");

        btn_cargarResultados.setText("Cargar resultados");
        btn_cargarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarResultadosActionPerformed(evt);
            }
        });

        btn_cargarPuntuacion.setText("Cargar puntuación");
        btn_cargarPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarPuntuacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblComentario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cargarResultados)
                                .addGap(53, 53, 53)
                                .addComponent(btn_cargarPuntuacion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnVerificar)
                                        .addGap(59, 59, 59)
                                        .addComponent(lblResultado))
                                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cargarResultados)
                    .addComponent(btn_cargarPuntuacion))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificar)
                    .addComponent(lblResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblComentario))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerificarMouseClicked

       
        
        String Password = new String(txtContrasena.getPassword());
        Scanner scan = new Scanner(System.in);
      
        
        if (Password.length()< linea1)
        {
           lblComentario.setText("La contraseña no pude tener menos de" + String.valueOf(linea1) + "caracteres..."); 
        }
        else
        {
            int Puntuacion = 0;  
            int Mayuscula = 0; 
            int Minuscula = 0;
            int Numeros = 0;
            int Simbolos = 0;
            
           lblComentario.setText(""); 
           
           //Puntuación= (Número de la segunda línea) * (largo de contraseña ingresada)
           Puntuacion += linea2*Password.length();
           
           //Encontrar las mayúsculas, minúsculas, símbolos y números
            for (int i = 0; i < Password.length(); i++) {
                char ch = Password.charAt(i);
                
                if (ch>= 'A' && ch <='Z') {
                    Mayuscula++;
                }
                else if (ch>='a' && ch<='z') {
                    Minuscula++;
                }
                else if (ch == '/' || ch == '¿' || ch == '%' || ch == '$' || ch == '#' ) {
                    Simbolos++;
                }
                else {
                    Numeros++;
                }
            }
            
            //Puntuación= Puntuación + [(Número de la tercer línea)*(total de Mayúsculas ingresadas)]
            if (Mayuscula != 0) {
                
                Puntuacion += linea3*Mayuscula;
            }
            
            
            //Puntuación= Puntuación+ [(total de letras ingresadas)+ (Número de la cuarta línea)
            if (Mayuscula != 0 || Minuscula != 0) {
                
                Puntuacion += Mayuscula + Minuscula + linea4;
            }
            
            //Puntuación= Puntuación+ [(total de números ingresados)+ (Número de la quinta línea)
            if (Numeros != 0) {
                Puntuacion += Numeros + linea5;
            }
            
            //Puntuación= Puntuación + (total de símbolos ingresados) *[(largo de cadena) + (Número de la sexta línea) [/¿?%$#]
            if (Simbolos != 0) {
                
                Puntuacion += Simbolos * (Password.length() + linea6);
            }         
            
            //Si hay sólo letras: Puntuación – (Número de la séptima línea)
            if (Numeros == 0 && Simbolos == 0) {
                
                Puntuacion -= linea7;
            }
            
            //Si hay sólo números: Puntuación – (Número de la octava línea)
            
            if (Mayuscula == 0 && Minuscula == 0 && Simbolos == 0) {
                
                Puntuacion -= linea8;
            }
            
            //Imprimir comentario sobre seguridad de contraseña
            
            if (Puntuacion >= inf1 && Puntuacion <= sup1) {
                
                lblComentario.setText("Contraseña Insegura...");
            }
            else if (Puntuacion >= inf2 && Puntuacion <= sup2) {
                
                lblComentario.setText("Contraseña poco Segura...");
            }
            else if (Puntuacion >= inf3 && Puntuacion <= sup3) {
                
                lblComentario.setText("Contraseña Segura...");
            }
            else if (Puntuacion >= inf4 && Puntuacion <= sup4) {
                
                lblComentario.setText("Contraseña muy Segura...");
            }
            
            lblResultado.setText(String.valueOf(Puntuacion));
            
            
               
           
        }
        
        
    }//GEN-LAST:event_btnVerificarMouseClicked

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btn_cargarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarResultadosActionPerformed
     JFileChooser accion = null;       //variable escogedor de archivos
     File archivo = null;              //variable de tipo File, guarda la información del archivo seleccionado
     accion = new JFileChooser("./");  //abre en la ruta (./) que es la ruta del proyecto
     accion.setFileSelectionMode(0);
     FileNameExtensionFilter filtro = new FileNameExtensionFilter("TXT", "txt"); //creamos filtro
     accion.setFileFilter(filtro); //aplicamos filtro
     accion.setDialogTitle("Abrir archivo"); // Titulo de la ventana de selección de 
     
     if (accion.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { //caso en que escogimos archivos.
            archivo = accion.getSelectedFile(); //archivo va a ser igual al archivo que escogimos
            System.out.println(accion.getSelectedFile().toString()); //Imprimir ruta de mi archivo
            try {
                /*Si existe el fichero*/
                if (archivo.exists()) {
                    FileReader lectura = new FileReader(archivo);
                    String texto = "", linea = "";
                    BufferedReader br = new BufferedReader(lectura);
                    String[] accion_archivo;
                    
                    int cont=1;
                    while ((linea = br.readLine()) != null) {
                        accion_archivo = linea.split(","); // separar el archivo de texto
                        if(cont == 1){
                            inf1 = Integer.parseInt(accion_archivo[0]);
                            sup1 = Integer.parseInt(accion_archivo[1]);
                        }
                        else if(cont == 2){
                            inf2 = Integer.parseInt(accion_archivo[0]);
                            sup2 = Integer.parseInt(accion_archivo[1]);
                        }
                        else if(cont == 3){
                            inf3 = Integer.parseInt(accion_archivo[0]);
                            sup3 = Integer.parseInt(accion_archivo[1]);
                        }
                        else if(cont == 4){
                            inf4 = Integer.parseInt(accion_archivo[0]);
                            sup4 = Integer.parseInt(accion_archivo[1]);
                        }
                        
                        cont++;
                    }
                    System.out.println("");
                    
                } else {
                    System.out.println("Fichero No Existe");
                }
            } catch (Exception ex) {
                /*Captura un posible error y le imprime n pantalla*/
                System.out.println(ex.getMessage());
            }
        } else { // caso en que no escogimos archivo.
            System.out.println("No se selecciono archivo");
        }
        
    }//GEN-LAST:event_btn_cargarResultadosActionPerformed

    private void btn_cargarPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarPuntuacionActionPerformed
     JFileChooser accion = null;       //variable escogedor de archivos
     File archivo = null;              //variable de tipo File, guarda la información del archivo seleccionado
     accion = new JFileChooser("./");  //abre en la ruta (./) que es la ruta del proyecto
     accion.setFileSelectionMode(0);
     FileNameExtensionFilter filtro = new FileNameExtensionFilter("TXT", "txt"); //creamos filtro
     accion.setFileFilter(filtro); //aplicamos filtro
     accion.setDialogTitle("Abrir archivo"); // Titulo de la ventana de selección de 
     
     if (accion.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { //caso en que escogimos archivos.
            archivo = accion.getSelectedFile(); //archivo va a ser igual al archivo que escogimos
            System.out.println(accion.getSelectedFile().toString()); //Imprimir ruta de mi archivo
            try {
                /*Si existe el fichero*/
                if (archivo.exists()) {
                    FileReader lectura = new FileReader(archivo);
                    String texto = "", linea = "";
                    BufferedReader br = new BufferedReader(lectura);
                    String[] accion_archivo;
                    
                    int cont=1;
                    while ((linea = br.readLine()) != null) {
                        accion_archivo = linea.split(";"); // separar el archivo de texto
                        if(cont == 1){
                            linea1 = Integer.parseInt(accion_archivo[0]);
                        }
                        else if(cont == 2){
                            linea2 = Integer.parseInt(accion_archivo[0]);
                        }
                        else if(cont == 3){
                            linea3 = Integer.parseInt(accion_archivo[0]); 
                        }
                        else if(cont == 4){
                            linea4 = Integer.parseInt(accion_archivo[0]); 
                        }
                        else if(cont == 5){
                            linea5 = Integer.parseInt(accion_archivo[0]); 
                        }
                        else if(cont == 6){
                            linea6 = Integer.parseInt(accion_archivo[0]); 
                        }
                        else if(cont == 7){
                            linea7 = Integer.parseInt(accion_archivo[0]); 
                        }
                        else if(cont == 8){
                            linea8 = Integer.parseInt(accion_archivo[0]); 
                        }
                        
                        cont++;
                    }
                    System.out.println("");
                    
                } else {
                    System.out.println("Fichero No Existe");
                }
            } catch (Exception ex) {
                /*Captura un posible error y le imprime n pantalla*/
                System.out.println(ex.getMessage());
            }
        } else { // caso en que no escogimos archivo.
            System.out.println("No se selecciono archivo");
        } 
    }//GEN-LAST:event_btn_cargarPuntuacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btn_cargarPuntuacion;
    private javax.swing.JButton btn_cargarResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables
}
